# Generated by Django 3.0.6 on 2022-05-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='date',
            new_name='pub_date',
        ),
    ]
